<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MpvShell.Player.Abstractions\MpvShell.Player.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Native\native-dependencies.lock.json"
          CopyToOutputDirectory="PreserveNewest"
          TargetPath="runtimes\win-x64\native\native-dependencies.json" />
  </ItemGroup>

</Project>
